# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-29 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperApp', '0004_user_dob'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
