# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='PyBelt_app.User')),
                ('wishers', models.ManyToManyField(related_name='items', to='PyBelt_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='yourwishitems',
            field=models.ManyToManyField(default=None, related_name='favorites', to='PyBelt_app.Wish'),
        ),
    ]
